### PR TITLE
updating to use v3 dividends and splits API (with .gte .lte filters)

### PR DESCRIPTION
**Pull request by ivoytov**
I wasn't sure how to handle keyword arguments with periods in them like `ex_dividend_date.gte` so I came up with this solution.

### CODE REVIEW

**Comment by ivoytov** [comment]
Here is how I use the API:

```
params = Dict(Symbol("ex_dividend_date.gte") => "2022-12-25", :limit => 1000)
raw = stock_dividends(opts, security.ticker; params)
```

**Comment by PyDataBlog** [comment]
> Here is how I use the API:
> 
> 
> 
> ```
> 
> params = Dict(Symbol("ex_dividend_date.gte") => "2022-12-25", :limit => 1000)
> 
> raw = stock_dividends(opts, security.ticker; params)
> 
> ```

LGTM

**Comment by ivoytov** [comment]
Updated the test suite to make it work as well. Note for some reason I had to add TypedTables and ConfigEnv to the Project.toml file to make it compile and run.

**Comment by PyDataBlog** [comment]
> Updated the test suite to make it work as well. Note for some reason I had to add TypedTables and ConfigEnv to the Project.toml file to make it compile and run.

Can you update the dependencies as well? Seems upstream packages have been updated a lot so package is lagging way too behind.

**Comment by ivoytov** [comment]
Ok added those 2 dependencies that were missing and rang `]update` but it didn't change anything else. From the build log it seems like the build script is failing because it's missing the `API_KEY` variable. Not sure how you got it to work with your private key in the first place!

**Comment by PyDataBlog** [comment]
> Ok added those 2 dependencies that were missing and rang `]update` but it didn't change anything else. From the build log it seems like the build script is failing because it's missing the `API_KEY` variable. Not sure how you got it to work with your private key in the first place!

Key was working fine up until now so I guess it's because the workflow also needs updating. The API_KEY is tied to a linked secret. I will look at it tonight as well. Appreciate the updates. Feel free to join the maintenance of the package if you are up for it.

**Comment by ivoytov** [comment]
Curious if maybe the key doesn’t work since it’s running on a PR that’s not coming from you, but from my fork of the codebase.

**Pull request merged**
